QT       += quick opengl


TARGET = cpp-tests
DESTDIR = ../lib
TEMPLATE = lib
CONFIG += staticlib

CONFIG += c++11
CONFIG += precompile_header

DEFINES += CC_TARGET_OS_MAC=1

PRECOMPILED_HEADER  += precompiled.h

include(../cocos2d-qt/cocos2dx.pri)

INCLUDEPATH += \
$$PWD/../../external/chipmunk/include/chipmunk \
$$PWD/../../external \
$$PWD/../../cocos/editor-support \
$$PWD/../.. \
Classes



SOURCES += \
    Classes/ActionManagerTest/ActionManagerTest.cpp \
    Classes/ActionsEaseTest/ActionsEaseTest.cpp \
    Classes/ActionsProgressTest/ActionsProgressTest.cpp \
    Classes/ActionsTest/ActionsTest.cpp \
    Classes/Box2DTest/Box2dTest.cpp \
    Classes/Box2DTestBed/Box2dView.cpp \
    Classes/Box2DTestBed/GLES-Render.cpp \
    Classes/Box2DTestBed/Test.cpp \
    Classes/Box2DTestBed/TestEntries.cpp \
    Classes/BugsTest/Bug-458/Bug-458.cpp \
    Classes/BugsTest/Bug-458/QuestionContainerSprite.cpp \
    Classes/BugsTest/Bug-1159.cpp \
    Classes/BugsTest/Bug-1174.cpp \
    Classes/BugsTest/Bug-350.cpp \
    Classes/BugsTest/Bug-422.cpp \
    Classes/BugsTest/Bug-624.cpp \
    Classes/BugsTest/Bug-886.cpp \
    Classes/BugsTest/Bug-899.cpp \
    Classes/BugsTest/Bug-914.cpp \
    Classes/BugsTest/Bug-Child.cpp \
    Classes/BugsTest/BugsTest.cpp \
    Classes/ChipmunkTest/ChipmunkTest.cpp \
    Classes/ClickAndMoveTest/ClickAndMoveTest.cpp \
    Classes/ClippingNodeTest/ClippingNodeTest.cpp \
    Classes/CocosDenshionTest/CocosDenshionTest.cpp \
    Classes/ConfigurationTest/ConfigurationTest.cpp \
    Classes/ConsoleTest/ConsoleTest.cpp \
    Classes/CurlTest/CurlTest.cpp \
    Classes/CurrentLanguageTest/CurrentLanguageTest.cpp \
    Classes/DataVisitorTest/DataVisitorTest.cpp \
    Classes/DrawPrimitivesTest/DrawPrimitivesTest.cpp \
    Classes/EffectsAdvancedTest/EffectsAdvancedTest.cpp \
    Classes/EffectsTest/EffectsTest.cpp \
    Classes/ExtensionsTest/CocosBuilderTest/AnimationsTest/AnimationsTestLayer.cpp \
    Classes/ExtensionsTest/CocosBuilderTest/ButtonTest/ButtonTestLayer.cpp \
    Classes/ExtensionsTest/CocosBuilderTest/HelloCocosBuilder/HelloCocosBuilderLayer.cpp \
    Classes/ExtensionsTest/CocosBuilderTest/MenuTest/MenuTestLayer.cpp \
    Classes/ExtensionsTest/CocosBuilderTest/TestHeader/TestHeaderLayer.cpp \
    Classes/ExtensionsTest/CocosBuilderTest/TimelineCallbackTest/TimelineCallbackTestLayer.cpp \
    Classes/ExtensionsTest/CocosBuilderTest/CocosBuilderTest.cpp \
    Classes/ExtensionsTest/CocoStudioActionTimelineTest/ActionTimelineTestScene.cpp \
    Classes/ExtensionsTest/CocoStudioArmatureTest/ArmatureScene.cpp \
    Classes/ExtensionsTest/CocoStudioComponentsTest/ComponentsTestScene.cpp \
    Classes/ExtensionsTest/CocoStudioComponentsTest/EnemyController.cpp \
    Classes/ExtensionsTest/CocoStudioComponentsTest/GameOverScene.cpp \
    Classes/ExtensionsTest/CocoStudioComponentsTest/PlayerController.cpp \
    Classes/ExtensionsTest/CocoStudioComponentsTest/ProjectileController.cpp \
    Classes/ExtensionsTest/CocoStudioComponentsTest/SceneController.cpp \
    Classes/ExtensionsTest/CocoStudioSceneTest/TriggerCode/acts.cpp \
    Classes/ExtensionsTest/CocoStudioSceneTest/TriggerCode/cons.cpp \
    Classes/ExtensionsTest/CocoStudioSceneTest/SceneEditorTest.cpp \
    Classes/ExtensionsTest/ControlExtensionTest/CCControlButtonTest/CCControlButtonTest.cpp \
    Classes/ExtensionsTest/ControlExtensionTest/CCControlColourPicker/CCControlColourPickerTest.cpp \
    Classes/ExtensionsTest/ControlExtensionTest/CCControlPotentiometerTest/CCControlPotentiometerTest.cpp \
    Classes/ExtensionsTest/ControlExtensionTest/CCControlSliderTest/CCControlSliderTest.cpp \
    Classes/ExtensionsTest/ControlExtensionTest/CCControlStepperTest/CCControlStepperTest.cpp \
    Classes/ExtensionsTest/ControlExtensionTest/CCControlSwitchTest/CCControlSwitchTest.cpp \
    Classes/ExtensionsTest/ControlExtensionTest/CCControlScene.cpp \
    Classes/ExtensionsTest/ControlExtensionTest/CCControlSceneManager.cpp \
    Classes/ExtensionsTest/EditBoxTest/EditBoxTest.cpp \
    Classes/ExtensionsTest/NetworkTest/HttpClientTest.cpp \
    Classes/ExtensionsTest/NetworkTest/SocketIOTest.cpp \
    Classes/ExtensionsTest/NetworkTest/WebSocketTest.cpp \
    Classes/ExtensionsTest/NotificationCenterTest/NotificationCenterTest.cpp \
    Classes/ExtensionsTest/Scale9SpriteTest/Scale9SpriteTest.cpp \
    Classes/ExtensionsTest/TableViewTest/CustomTableViewCell.cpp \
    Classes/ExtensionsTest/TableViewTest/TableViewTestScene.cpp \
    Classes/ExtensionsTest/ExtensionsTest.cpp \
    Classes/FileUtilsTest/FileUtilsTest.cpp \
    Classes/FontTest/FontTest.cpp \
    Classes/InputTest/MouseTest.cpp \
    Classes/IntervalTest/IntervalTest.cpp \
    Classes/LabelTest/LabelTest.cpp \
    Classes/LabelTest/LabelTestNew.cpp \
    Classes/LayerTest/LayerTest.cpp \
    Classes/MenuTest/MenuTest.cpp \
    Classes/MotionStreakTest/MotionStreakTest.cpp \
    Classes/MutiTouchTest/MutiTouchTest.cpp \
    Classes/NewEventDispatcherTest/NewEventDispatcherTest.cpp \
    Classes/NewRendererTest/NewRendererTest.cpp \
    Classes/NodeTest/NodeTest.cpp \
    Classes/ParallaxTest/ParallaxTest.cpp \
    Classes/ParticleTest/ParticleTest.cpp \
    Classes/PerformanceTest/PerformanceAllocTest.cpp \
    Classes/PerformanceTest/PerformanceCallbackTest.cpp \
    Classes/PerformanceTest/PerformanceContainerTest.cpp \
    Classes/PerformanceTest/PerformanceEventDispatcherTest.cpp \
    Classes/PerformanceTest/PerformanceLabelTest.cpp \
    Classes/PerformanceTest/PerformanceNodeChildrenTest.cpp \
    Classes/PerformanceTest/PerformanceParticleTest.cpp \
    Classes/PerformanceTest/PerformanceRendererTest.cpp \
    Classes/PerformanceTest/PerformanceScenarioTest.cpp \
    Classes/PerformanceTest/PerformanceSpriteTest.cpp \
    Classes/PerformanceTest/PerformanceTest.cpp \
    Classes/PerformanceTest/PerformanceTextureTest.cpp \
    Classes/PerformanceTest/PerformanceTouchesTest.cpp \
    Classes/PhysicsTest/PhysicsTest.cpp \
    Classes/ReleasePoolTest/ReleasePoolTest.cpp \
    Classes/RenderTextureTest/RenderTextureTest.cpp \
    Classes/RotateWorldTest/RotateWorldTest.cpp \
    Classes/SceneTest/SceneTest.cpp \
    Classes/SchedulerTest/SchedulerTest.cpp \
    Classes/ShaderTest/ShaderTest.cpp \
    Classes/ShaderTest/ShaderTest2.cpp \
    Classes/SpineTest/SpineTest.cpp \
    Classes/Sprite3DTest/Sprite3DTest.cpp \
    Classes/SpriteTest/SpriteTest.cpp \
    Classes/TextInputTest/TextInputTest.cpp \
    Classes/Texture2dTest/Texture2dTest.cpp \
    Classes/TextureCacheTest/TextureCacheTest.cpp \
    Classes/TexturePackerEncryptionTest/TextureAtlasEncryptionTest.cpp \
    Classes/TileMapTest/TileMapTest.cpp \
    Classes/TileMapTest/TileMapTest2.cpp \
    Classes/TouchesTest/Ball.cpp \
    Classes/TouchesTest/Paddle.cpp \
    Classes/TouchesTest/TouchesTest.cpp \
    Classes/TransitionsTest/TransitionsTest.cpp \
    Classes/UITest/CocoStudioGUITest/CocostudioParserTest/CocostudioParserJsonTest.cpp \
    Classes/UITest/CocoStudioGUITest/CustomTest/CustomImageTest/CustomImageTest.cpp \
    Classes/UITest/CocoStudioGUITest/CustomTest/CustomParticleWidgetTest/CustomParticleWidgetTest.cpp \
    Classes/UITest/CocoStudioGUITest/CustomWidget/CustomImageView.cpp \
    Classes/UITest/CocoStudioGUITest/CustomWidget/CustomImageViewReader.cpp \
    Classes/UITest/CocoStudioGUITest/CustomWidget/CustomParticleWidget.cpp \
    Classes/UITest/CocoStudioGUITest/CustomWidget/CustomParticleWidgetReader.cpp \
    Classes/UITest/CocoStudioGUITest/CustomWidget/CustomReader.cpp \
    Classes/UITest/CocoStudioGUITest/UIButtonTest/UIButtonTest.cpp \
    Classes/UITest/CocoStudioGUITest/UIButtonTest/UIButtonTest_Editor.cpp \
    Classes/UITest/CocoStudioGUITest/UICheckBoxTest/UICheckBoxTest.cpp \
    Classes/UITest/CocoStudioGUITest/UICheckBoxTest/UICheckBoxTest_Editor.cpp \
    Classes/UITest/CocoStudioGUITest/UIFocusTest/UIFocusTest.cpp \
    Classes/UITest/CocoStudioGUITest/UIImageViewTest/UIImageViewTest.cpp \
    Classes/UITest/CocoStudioGUITest/UIImageViewTest/UIImageViewTest_Editor.cpp \
    Classes/UITest/CocoStudioGUITest/UILayoutTest/UILayoutTest.cpp \
    Classes/UITest/CocoStudioGUITest/UILayoutTest/UILayoutTest_Editor.cpp \
    Classes/UITest/CocoStudioGUITest/UIListViewTest/UIListViewTest.cpp \
    Classes/UITest/CocoStudioGUITest/UIListViewTest/UIListViewTest_Editor.cpp \
    Classes/UITest/CocoStudioGUITest/UILoadingBarTest/UILoadingBarTest.cpp \
    Classes/UITest/CocoStudioGUITest/UILoadingBarTest/UILoadingBarTest_Editor.cpp \
    Classes/UITest/CocoStudioGUITest/UIPageViewTest/UIPageViewTest.cpp \
    Classes/UITest/CocoStudioGUITest/UIPageViewTest/UIPageViewTest_Editor.cpp \
    Classes/UITest/CocoStudioGUITest/UIRichTextTest/UIRichTextTest.cpp \
    Classes/UITest/CocoStudioGUITest/UIScrollViewTest/UIScrollViewTest.cpp \
    Classes/UITest/CocoStudioGUITest/UIScrollViewTest/UIScrollViewTest_Editor.cpp \
    Classes/UITest/CocoStudioGUITest/UISliderTest/UISliderTest.cpp \
    Classes/UITest/CocoStudioGUITest/UISliderTest/UISliderTest_Editor.cpp \
    Classes/UITest/CocoStudioGUITest/UITextAtlasTest/UITextAtlasTest.cpp \
    Classes/UITest/CocoStudioGUITest/UITextAtlasTest/UITextAtlasTest_Editor.cpp \
    Classes/UITest/CocoStudioGUITest/UITextBMFontTest/UITextBMFontTest.cpp \
    Classes/UITest/CocoStudioGUITest/UITextBMFontTest/UITextBMFontTest_Editor.cpp \
    Classes/UITest/CocoStudioGUITest/UITextFieldTest/UITextFieldTest.cpp \
    Classes/UITest/CocoStudioGUITest/UITextFieldTest/UITextFieldTest_Editor.cpp \
    Classes/UITest/CocoStudioGUITest/UITextTest/UITextTest.cpp \
    Classes/UITest/CocoStudioGUITest/UITextTest/UITextTest_Editor.cpp \
#    Classes/UITest/CocoStudioGUITest/UIVideoPlayerTest/UIVideoPlayerTest.cpp \
    Classes/UITest/CocoStudioGUITest/UIWidgetAddNodeTest/UIWidgetAddNodeTest.cpp \
    Classes/UITest/CocoStudioGUITest/UIWidgetAddNodeTest/UIWidgetAddNodeTest_Editor.cpp \
    Classes/UITest/CocoStudioGUITest/CocosGUIScene.cpp \
    Classes/UITest/CocoStudioGUITest/CocoStudioGUITest.cpp \
    Classes/UITest/CocoStudioGUITest/CocostudioParserTest.cpp \
    Classes/UITest/CocoStudioGUITest/CustomGUIScene.cpp \
    Classes/UITest/CocoStudioGUITest/GUIEditorTest.cpp \
    Classes/UITest/CocoStudioGUITest/UIScale9SpriteTest.cpp \
    Classes/UITest/CocoStudioGUITest/UIScene.cpp \
    Classes/UITest/CocoStudioGUITest/UIScene_Editor.cpp \
    Classes/UITest/CocoStudioGUITest/UISceneManager.cpp \
    Classes/UITest/CocoStudioGUITest/UISceneManager_Editor.cpp \
    Classes/UITest/UITest.cpp \
    Classes/UnitTest/RefPtrTest.cpp \
    Classes/UnitTest/UnitTest.cpp \
    Classes/UserDefaultTest/UserDefaultTest.cpp \
    Classes/ZwoptexTest/ZwoptexTest.cpp \
    Classes/AppDelegate.cpp \
    Classes/BaseTest.cpp \
    Classes/controller.cpp \
    Classes/testBasic.cpp \
    Classes/VisibleRect.cpp

HEADERS += precompiled.h \
    Classes/ActionManagerTest/ActionManagerTest.h \
    Classes/ActionsEaseTest/ActionsEaseTest.h \
    Classes/ActionsProgressTest/ActionsProgressTest.h \
    Classes/ActionsTest/ActionsTest.h \
    Classes/Box2DTest/Box2dTest.h \
    Classes/Box2DTestBed/Tests/AddPair.h \
    Classes/Box2DTestBed/Tests/ApplyForce.h \
    Classes/Box2DTestBed/Tests/BodyTypes.h \
    Classes/Box2DTestBed/Tests/Breakable.h \
    Classes/Box2DTestBed/Tests/Bridge.h \
    Classes/Box2DTestBed/Tests/BulletTest.h \
    Classes/Box2DTestBed/Tests/Cantilever.h \
    Classes/Box2DTestBed/Tests/Car.h \
    Classes/Box2DTestBed/Tests/Chain.h \
    Classes/Box2DTestBed/Tests/CharacterCollision.h \
    Classes/Box2DTestBed/Tests/CollisionFiltering.h \
    Classes/Box2DTestBed/Tests/CollisionProcessing.h \
    Classes/Box2DTestBed/Tests/CompoundShapes.h \
    Classes/Box2DTestBed/Tests/Confined.h \
    Classes/Box2DTestBed/Tests/ContinuousTest.h \
    Classes/Box2DTestBed/Tests/ConvexHull.h \
    Classes/Box2DTestBed/Tests/ConveyorBelt.h \
    Classes/Box2DTestBed/Tests/DistanceTest.h \
    Classes/Box2DTestBed/Tests/Dominos.h \
    Classes/Box2DTestBed/Tests/DumpShell.h \
    Classes/Box2DTestBed/Tests/DynamicTreeTest.h \
    Classes/Box2DTestBed/Tests/EdgeShapes.h \
    Classes/Box2DTestBed/Tests/EdgeTest.h \
    Classes/Box2DTestBed/Tests/Gears.h \
    Classes/Box2DTestBed/Tests/Mobile.h \
    Classes/Box2DTestBed/Tests/MobileBalanced.h \
    Classes/Box2DTestBed/Tests/MotorJoint.h \
    Classes/Box2DTestBed/Tests/OneSidedPlatform.h \
    Classes/Box2DTestBed/Tests/Pinball.h \
    Classes/Box2DTestBed/Tests/PolyCollision.h \
    Classes/Box2DTestBed/Tests/PolyShapes.h \
    Classes/Box2DTestBed/Tests/Prismatic.h \
    Classes/Box2DTestBed/Tests/Pulleys.h \
    Classes/Box2DTestBed/Tests/Pyramid.h \
    Classes/Box2DTestBed/Tests/RayCast.h \
    Classes/Box2DTestBed/Tests/Revolute.h \
    Classes/Box2DTestBed/Tests/Rope.h \
    Classes/Box2DTestBed/Tests/RopeJoint.h \
    Classes/Box2DTestBed/Tests/SensorTest.h \
    Classes/Box2DTestBed/Tests/ShapeEditing.h \
    Classes/Box2DTestBed/Tests/SliderCrank.h \
    Classes/Box2DTestBed/Tests/SphereStack.h \
    Classes/Box2DTestBed/Tests/TheoJansen.h \
    Classes/Box2DTestBed/Tests/Tiles.h \
    Classes/Box2DTestBed/Tests/TimeOfImpact.h \
    Classes/Box2DTestBed/Tests/Tumbler.h \
    Classes/Box2DTestBed/Tests/VaryingFriction.h \
    Classes/Box2DTestBed/Tests/VaryingRestitution.h \
    Classes/Box2DTestBed/Tests/VerticalStack.h \
    Classes/Box2DTestBed/Tests/Web.h \
    Classes/Box2DTestBed/Box2dView.h \
    Classes/Box2DTestBed/GLES-Render.h \
    Classes/Box2DTestBed/Test.h \
    Classes/BugsTest/Bug-458/Bug-458.h \
    Classes/BugsTest/Bug-458/QuestionContainerSprite.h \
    Classes/BugsTest/Bug-1159.h \
    Classes/BugsTest/Bug-1174.h \
    Classes/BugsTest/Bug-350.h \
    Classes/BugsTest/Bug-422.h \
    Classes/BugsTest/Bug-624.h \
    Classes/BugsTest/Bug-886.h \
    Classes/BugsTest/Bug-899.h \
    Classes/BugsTest/Bug-914.h \
    Classes/BugsTest/Bug-Child.h \
    Classes/BugsTest/BugsTest.h \
    Classes/ChipmunkTest/ChipmunkTest.h \
    Classes/ClickAndMoveTest/ClickAndMoveTest.h \
    Classes/ClippingNodeTest/ClippingNodeTest.h \
    Classes/CocosDenshionTest/CocosDenshionTest.h \
    Classes/ConfigurationTest/ConfigurationTest.h \
    Classes/ConsoleTest/ConsoleTest.h \
    Classes/CurlTest/CurlTest.h \
    Classes/CurrentLanguageTest/CurrentLanguageTest.h \
    Classes/DataVisitorTest/DataVisitorTest.h \
    Classes/DrawPrimitivesTest/DrawPrimitivesTest.h \
    Classes/EffectsAdvancedTest/EffectsAdvancedTest.h \
    Classes/EffectsTest/EffectsTest.h \
    Classes/ExtensionsTest/CocosBuilderTest/AnimationsTest/AnimationsLayerLoader.h \
    Classes/ExtensionsTest/CocosBuilderTest/AnimationsTest/AnimationsTestLayer.h \
    Classes/ExtensionsTest/CocosBuilderTest/ButtonTest/ButtonTestLayer.h \
    Classes/ExtensionsTest/CocosBuilderTest/ButtonTest/ButtonTestLayerLoader.h \
    Classes/ExtensionsTest/CocosBuilderTest/HelloCocosBuilder/HelloCocosBuilderLayer.h \
    Classes/ExtensionsTest/CocosBuilderTest/HelloCocosBuilder/HelloCocosBuilderLayerLoader.h \
    Classes/ExtensionsTest/CocosBuilderTest/LabelTest/LabelTestLayer.h \
    Classes/ExtensionsTest/CocosBuilderTest/LabelTest/LabelTestLayerLoader.h \
    Classes/ExtensionsTest/CocosBuilderTest/MenuTest/MenuTestLayer.h \
    Classes/ExtensionsTest/CocosBuilderTest/MenuTest/MenuTestLayerLoader.h \
    Classes/ExtensionsTest/CocosBuilderTest/ParticleSystemTest/ParticleSystemTestLayer.h \
    Classes/ExtensionsTest/CocosBuilderTest/ParticleSystemTest/ParticleSystemTestLayerLoader.h \
    Classes/ExtensionsTest/CocosBuilderTest/ScrollViewTest/ScrollViewTestLayer.h \
    Classes/ExtensionsTest/CocosBuilderTest/ScrollViewTest/ScrollViewTestLayerLoader.h \
    Classes/ExtensionsTest/CocosBuilderTest/SpriteTest/SpriteTestLayer.h \
    Classes/ExtensionsTest/CocosBuilderTest/SpriteTest/SpriteTestLayerLoader.h \
    Classes/ExtensionsTest/CocosBuilderTest/TestHeader/TestHeaderLayer.h \
    Classes/ExtensionsTest/CocosBuilderTest/TestHeader/TestHeaderLayerLoader.h \
    Classes/ExtensionsTest/CocosBuilderTest/TimelineCallbackTest/TimelineCallbackLayerLoader.h \
    Classes/ExtensionsTest/CocosBuilderTest/TimelineCallbackTest/TimelineCallbackTestLayer.h \
    Classes/ExtensionsTest/CocosBuilderTest/CocosBuilderTest.h \
    Classes/ExtensionsTest/CocoStudioActionTimelineTest/ActionTimelineTestScene.h \
    Classes/ExtensionsTest/CocoStudioArmatureTest/ArmatureScene.h \
    Classes/ExtensionsTest/CocoStudioComponentsTest/ComponentsTestScene.h \
    Classes/ExtensionsTest/CocoStudioComponentsTest/EnemyController.h \
    Classes/ExtensionsTest/CocoStudioComponentsTest/GameOverScene.h \
    Classes/ExtensionsTest/CocoStudioComponentsTest/PlayerController.h \
    Classes/ExtensionsTest/CocoStudioComponentsTest/ProjectileController.h \
    Classes/ExtensionsTest/CocoStudioComponentsTest/SceneController.h \
    Classes/ExtensionsTest/CocoStudioSceneTest/TriggerCode/acts.h \
    Classes/ExtensionsTest/CocoStudioSceneTest/TriggerCode/cons.h \
    Classes/ExtensionsTest/CocoStudioSceneTest/TriggerCode/EventDef.h \
    Classes/ExtensionsTest/CocoStudioSceneTest/SceneEditorTest.h \
    Classes/ExtensionsTest/ControlExtensionTest/CCControlButtonTest/CCControlButtonTest.h \
    Classes/ExtensionsTest/ControlExtensionTest/CCControlColourPicker/CCControlColourPickerTest.h \
    Classes/ExtensionsTest/ControlExtensionTest/CCControlPotentiometerTest/CCControlPotentiometerTest.h \
    Classes/ExtensionsTest/ControlExtensionTest/CCControlSliderTest/CCControlSliderTest.h \
    Classes/ExtensionsTest/ControlExtensionTest/CCControlStepperTest/CCControlStepperTest.h \
    Classes/ExtensionsTest/ControlExtensionTest/CCControlSwitchTest/CCControlSwitchTest.h \
    Classes/ExtensionsTest/ControlExtensionTest/CCControlScene.h \
    Classes/ExtensionsTest/ControlExtensionTest/CCControlSceneManager.h \
    Classes/ExtensionsTest/EditBoxTest/EditBoxTest.h \
    Classes/ExtensionsTest/NetworkTest/HttpClientTest.h \
    Classes/ExtensionsTest/NetworkTest/SocketIOTest.h \
    Classes/ExtensionsTest/NetworkTest/WebSocketTest.h \
    Classes/ExtensionsTest/NotificationCenterTest/NotificationCenterTest.h \
    Classes/ExtensionsTest/Scale9SpriteTest/Scale9SpriteTest.h \
    Classes/ExtensionsTest/TableViewTest/CustomTableViewCell.h \
    Classes/ExtensionsTest/TableViewTest/TableViewTestScene.h \
    Classes/ExtensionsTest/ExtensionsTest.h \
    Classes/FileUtilsTest/FileUtilsTest.h \
    Classes/FontTest/FontTest.h \
    Classes/InputTest/MouseTest.h \
    Classes/IntervalTest/IntervalTest.h \
    Classes/LabelTest/LabelTest.h \
    Classes/LabelTest/LabelTestNew.h \
    Classes/LayerTest/LayerTest.h \
    Classes/MenuTest/MenuTest.h \
    Classes/MotionStreakTest/MotionStreakTest.h \
    Classes/MutiTouchTest/MutiTouchTest.h \
    Classes/NewEventDispatcherTest/NewEventDispatcherTest.h \
    Classes/NewRendererTest/NewRendererTest.h \
    Classes/NodeTest/NodeTest.h \
    Classes/ParallaxTest/ParallaxTest.h \
    Classes/ParticleTest/ParticleTest.h \
    Classes/PerformanceTest/PerformanceAllocTest.h \
    Classes/PerformanceTest/PerformanceCallbackTest.h \
    Classes/PerformanceTest/PerformanceContainerTest.h \
    Classes/PerformanceTest/PerformanceEventDispatcherTest.h \
    Classes/PerformanceTest/PerformanceLabelTest.h \
    Classes/PerformanceTest/PerformanceNodeChildrenTest.h \
    Classes/PerformanceTest/PerformanceParticleTest.h \
    Classes/PerformanceTest/PerformanceRendererTest.h \
    Classes/PerformanceTest/PerformanceScenarioTest.h \
    Classes/PerformanceTest/PerformanceSpriteTest.h \
    Classes/PerformanceTest/PerformanceTest.h \
    Classes/PerformanceTest/PerformanceTextureTest.h \
    Classes/PerformanceTest/PerformanceTouchesTest.h \
    Classes/PhysicsTest/PhysicsTest.h \
    Classes/ReleasePoolTest/ReleasePoolTest.h \
    Classes/RenderTextureTest/RenderTextureTest.h \
    Classes/RotateWorldTest/RotateWorldTest.h \
    Classes/SceneTest/SceneTest.h \
    Classes/SchedulerTest/SchedulerTest.h \
    Classes/ShaderTest/ShaderTest.h \
    Classes/ShaderTest/shaderTest.psh.h \
    Classes/ShaderTest/ShaderTest.vsh.h \
    Classes/ShaderTest/ShaderTest2.h \
    Classes/SpineTest/SpineTest.h \
    Classes/Sprite3DTest/Sprite3DTest.h \
    Classes/SpriteTest/SpriteTest.h \
    Classes/TextInputTest/TextInputTest.h \
    Classes/Texture2dTest/Texture2dTest.h \
    Classes/TextureCacheTest/TextureCacheTest.h \
    Classes/TexturePackerEncryptionTest/TextureAtlasEncryptionTest.h \
    Classes/TileMapTest/TileMapTest.h \
    Classes/TileMapTest/TileMapTest2.h \
    Classes/TouchesTest/Ball.h \
    Classes/TouchesTest/Paddle.h \
    Classes/TouchesTest/TouchesTest.h \
    Classes/TransitionsTest/TransitionsTest.h \
    Classes/UITest/CocoStudioGUITest/CocostudioParserTest/CocostudioParserJsonTest.h \
    Classes/UITest/CocoStudioGUITest/CustomTest/CustomImageTest/CustomImageTest.h \
    Classes/UITest/CocoStudioGUITest/CustomTest/CustomParticleWidgetTest/CustomParticleWidgetTest.h \
    Classes/UITest/CocoStudioGUITest/CustomWidget/CustomImageView.h \
    Classes/UITest/CocoStudioGUITest/CustomWidget/CustomImageViewReader.h \
    Classes/UITest/CocoStudioGUITest/CustomWidget/CustomParticleWidget.h \
    Classes/UITest/CocoStudioGUITest/CustomWidget/CustomParticleWidgetReader.h \
    Classes/UITest/CocoStudioGUITest/CustomWidget/CustomReader.h \
    Classes/UITest/CocoStudioGUITest/UIButtonTest/UIButtonTest.h \
    Classes/UITest/CocoStudioGUITest/UIButtonTest/UIButtonTest_Editor.h \
    Classes/UITest/CocoStudioGUITest/UICheckBoxTest/UICheckBoxTest.h \
    Classes/UITest/CocoStudioGUITest/UICheckBoxTest/UICheckBoxTest_Editor.h \
    Classes/UITest/CocoStudioGUITest/UIFocusTest/UIFocusTest.h \
    Classes/UITest/CocoStudioGUITest/UIImageViewTest/UIImageViewTest.h \
    Classes/UITest/CocoStudioGUITest/UIImageViewTest/UIImageViewTest_Editor.h \
    Classes/UITest/CocoStudioGUITest/UILayoutTest/UILayoutTest.h \
    Classes/UITest/CocoStudioGUITest/UILayoutTest/UILayoutTest_Editor.h \
    Classes/UITest/CocoStudioGUITest/UIListViewTest/UIListViewTest.h \
    Classes/UITest/CocoStudioGUITest/UIListViewTest/UIListViewTest_Editor.h \
    Classes/UITest/CocoStudioGUITest/UILoadingBarTest/UILoadingBarTest.h \
    Classes/UITest/CocoStudioGUITest/UILoadingBarTest/UILoadingBarTest_Editor.h \
    Classes/UITest/CocoStudioGUITest/UIPageViewTest/UIPageViewTest.h \
    Classes/UITest/CocoStudioGUITest/UIPageViewTest/UIPageViewTest_Editor.h \
    Classes/UITest/CocoStudioGUITest/UIRichTextTest/UIRichTextTest.h \
    Classes/UITest/CocoStudioGUITest/UIScrollViewTest/UIScrollViewTest.h \
    Classes/UITest/CocoStudioGUITest/UIScrollViewTest/UIScrollViewTest_Editor.h \
    Classes/UITest/CocoStudioGUITest/UISliderTest/UISliderTest.h \
    Classes/UITest/CocoStudioGUITest/UISliderTest/UISliderTest_Editor.h \
    Classes/UITest/CocoStudioGUITest/UITextAtlasTest/UITextAtlasTest.h \
    Classes/UITest/CocoStudioGUITest/UITextAtlasTest/UITextAtlasTest_Editor.h \
    Classes/UITest/CocoStudioGUITest/UITextBMFontTest/UITextBMFontTest.h \
    Classes/UITest/CocoStudioGUITest/UITextBMFontTest/UITextBMFontTest_Editor.h \
    Classes/UITest/CocoStudioGUITest/UITextFieldTest/UITextFieldTest.h \
    Classes/UITest/CocoStudioGUITest/UITextFieldTest/UITextFieldTest_Editor.h \
    Classes/UITest/CocoStudioGUITest/UITextTest/UITextTest.h \
    Classes/UITest/CocoStudioGUITest/UITextTest/UITextTest_Editor.h \
#    Classes/UITest/CocoStudioGUITest/UIVideoPlayerTest/UIVideoPlayerTest.h \
    Classes/UITest/CocoStudioGUITest/UIWidgetAddNodeTest/UIWidgetAddNodeTest.h \
    Classes/UITest/CocoStudioGUITest/UIWidgetAddNodeTest/UIWidgetAddNodeTest_Editor.h \
    Classes/UITest/CocoStudioGUITest/CocosGUIScene.h \
    Classes/UITest/CocoStudioGUITest/CocoStudioGUITest.h \
    Classes/UITest/CocoStudioGUITest/CocostudioParserTest.h \
    Classes/UITest/CocoStudioGUITest/CustomGUIScene.h \
    Classes/UITest/CocoStudioGUITest/GUIEditorTest.h \
    Classes/UITest/CocoStudioGUITest/UIScale9SpriteTest.h \
    Classes/UITest/CocoStudioGUITest/UIScene.h \
    Classes/UITest/CocoStudioGUITest/UIScene_Editor.h \
    Classes/UITest/CocoStudioGUITest/UISceneManager.h \
    Classes/UITest/CocoStudioGUITest/UISceneManager_Editor.h \
    Classes/UITest/UITest.h \
    Classes/UnitTest/RefPtrTest.h \
    Classes/UnitTest/UnitTest.h \
    Classes/UserDefaultTest/UserDefaultTest.h \
    Classes/ZwoptexTest/ZwoptexTest.h \
    Classes/AppDelegate.h \
    Classes/BaseTest.h \
    Classes/controller.h \
    Classes/testBasic.h \
    Classes/testResource.h \
    Classes/tests.h \
    Classes/VisibleRect.h


#unix {
#    target.path = /usr/lib
#    INSTALLS += target
#}
